service: app

provider:
    name: aws
    region: us-east-2
    runtime: provided

plugins:
    - ./vendor/bref/bref

functions:
    testFunction:
        handler: index.php
        events:
            - s3:
                  bucket: dmytrokot-images
                  event: s3:ObjectCreated:Put
        description: ''
        layers:
            - ${bref:layer.php-73}
    imageRekognitionFunction:
        handler: imageRekognition.php
        description: ''
        layers:
            - ${bref:layer.php-73}
    sendEmail:
        handler: sendEmail.php
        description: ''
        layers:
            - ${bref:layer.php-73}
    saveImageInfo:
        handler: saveImageInfo.php
        description: ''
        layers:
            - ${bref:layer.php-73}
    checkDogInPicture:
        handler: checkDogInPicture.php
        description: ''
        layers:
            - ${bref:layer.php-73}

# Exclude files from deployment
package:
    exclude:
        - 'tests/**'
